### ISSUE TITLE
图片预处理

### ISSUE THREAD

**Issue by KevinGong2013** [isee15/Card-Ocr#1]
你好我也在维护一个类似的repo，不过是运行在 iOS&macOS 平台的.

[纯`Swift4`使用`CNN`(卷积神经网络)识别身份证信息](https://github.com/KevinGong2013/ChineseIDCardOCR)

想和你交流一下图片预处理的过程，不知道有没有相关的资料推荐一下。

**Comment by isee15** [comment]
目前在图片已经提取出来的情况下，主要用opencv处理的。二值化，腐蚀，膨胀，轮廓检测。http://www.jianshu.com/p/ac4c4536ca3e
如果要从背景里面提取图片，比如手持的身份证，那么可以用深度学习的目标检测的一些方法RCNN->SPP->Fast RCNN->Faster RCNN->YOLO->SSD->YOLO2->Mask RCNN。之前看美团用的简化版的Faster RCNN。但我对RCNN还看不明白，也缺少训练样本。

**Comment by KevinGong2013** [comment]
如果身份证整体比较暗，直接二值化很难把身份证的底纹去掉，会大大影响识别率。

**Comment by isee15** [comment]
当需要适应不同亮度的时候，二值化的阈值可以动态算。比如opencv里面有THRESH_OTSU。
同时opencv里面有些降噪的方法比如fastNlMeansDenoisingColored也能把底纹过滤一些。

**Comment by KevinGong2013** [comment]
openCV的体积有点感人～

**Comment by isee15** [comment]
自己实现对应的算法也行，ostu算法大概100行

**Comment by o70078** [comment]
不知道图片摆正如何实现?
我之前尝试用opencv  寻找直线 + 透视变换,想把一个斜着拍的卡片摆正,不过效果很差.
楼主有什么好办法吗?

**Comment by KevinGong2013** [comment]
我用苹果提供的api 直接进行一次 透视矫正效果就蛮好了。你阔以试试看
