### ISSUE TITLE
关于您windows编译环境配置

### ISSUE THREAD

**Issue by qfwysw** [isee15/Card-Ocr#4]
感谢您优秀的代码和慷慨的开源.
我想简单注释掉很多输出, 但是我克隆了项目后vs2019打开并不能运行通, 我想请教一下您关于环境的配置

**Comment by isee15** [comment]
win10 VS2017

**Comment by qfwysw** [comment]
会出现找不到包的情况
![image](https://user-images.githubusercontent.com/53482524/133873032-c092ab02-bba2-4185-960e-ab486573b0bb.png)

**Comment by isee15** [comment]
用Release x64

**Comment by qfwysw** [comment]
十分感谢您的回答, 我已经正确执行了, 再次表达我的感谢!!!
