### ISSUE TITLE
请教一下如果身份证的地址有多行, 分成了几段识别如何拼凑回去

### ISSUE THREAD

**Issue by qfwysw** [isee15/Card-Ocr#5]
![image](https://user-images.githubusercontent.com/53482524/133919557-a8a29c0b-9789-4574-aa70-d8275c2d0d96.png)
十分感谢您的代码, 如果是上述地址, paddleocr往往会将地址切割成几段识别, 我该如何正确拼凑回去呢, 我尝试了ocr_rec中的ratio没有什么效果, 我的想法是原来的框增大能框住更大的范围, 但是现在看来这不是可行的方法. 请问您有什么好的解决方法吗?

**Comment by isee15** [comment]
用语义解决，根据坐标顺序做判断，只调整参数不行。

**Comment by qfwysw** [comment]
感谢您的回答, 我也是这么做的
